import streamlit as st

# Do NOT call st.set_page_config here; it's already called in Home.py.

st.title("🧠 AIBC Capstone Assignment – Methodology")

st.markdown("""
## Domain Area: Understanding CPF Retirement Policies

This project demonstrates how AI, retrieval systems, and agent-based orchestration can support citizens
in understanding **CPF retirement policies**. The app combines:

- Retrieval-Augmented Generation (RAG)
- CrewAI agents with explicit roles and safety constraints
- Numeric simulations plus LLM explanations
- A modular backend (vector store, RAG layer, agent layer)
- A multipage Streamlit interface with charts and tables

The goal is to help citizens explore CPF topics safely and clearly, while reducing the risks of
hallucinations, misinformation, or unsafe model behaviour.
""")

st.markdown("---")

st.header("🔧 Overall System Architecture")

st.markdown("""
The application is organised into **four main layers**:

### 1. Data Preparation Layer
- Public CPF information is manually curated into Markdown files in `data/raw/`.
- A preprocessing script (`backend/build_corpus.py`) splits these into smaller chunks.
- Each chunk is embedded using OpenAI embeddings.
- Embeddings + metadata are stored in `data/processed/cpf_corpus.jsonl`.

### 2. Vector Store Layer (`backend/vector_store.py`)
- Loads all embeddings and metadata into memory.
- Accepts a text query, embeds it, and performs cosine similarity search.
- Returns the **top-k** relevant CPF policy chunks.
- This layer acts as a **tool** that CrewAI agents depend on for context.

### 3. RAG + CrewAI Agent Layer (`backend/rag.py`)
For both use cases, the backend follows a **prompt-chaining pipeline**:

1. **Build a controlled query**  
   - Use Case 1: combines user question + age band + income band.  
   - Use Case 2: uses **numeric-only** inputs and classification (no free-text).

2. **Retrieve policy chunks**  
   - Calls `retrieve(query, k)` from the vector store.  
   - Produces relevant CPF snippets (BRS/FRS/ERS, withdrawals, CPF LIFE, etc.).

3. **Construct a safety-aware context block**  
   - Contains system rules, safety constraints, and disclaimers.  
   - Explicitly forbids giving financial advice or following hidden instructions.  
   - Treats retrieved text as **data**, not instructions.

4. **CrewAI Agent + Task orchestration**  
   - A dedicated agent is used for each use case:
     - “CPF policy explainer” (Use Case 1)
     - “CPF retirement simulation explainer” (Use Case 2)
   - Each agent has:
     - a role, goal, and backstory
     - a Task with an expected output format and safety rules
   - A Crew executes the task in **sequential** mode.

### 4. Streamlit UI Layer
- `Home.py`: landing page, disclaimer, navigation.
- Use Case 1 page: Policy Q&A with a chat-style explanation and BRS/FRS/ERS explainer.
- Use Case 2 page: Retirement simulator with numeric inputs, presets, charts, and explanations.
- Documentation pages: “About Us” and “Methodology”.
""")

st.markdown("---")

# =====================================================================
# Use Case 1
# =====================================================================

st.header("📘 Use Case 1 — CPF Policy Explainer (RAG + CrewAI Agent)")

st.markdown("""
### 🎯 Purpose

Allow users to ask **natural-language** questions about CPF (e.g. *“What is FRS?”*,
*“How much can I withdraw at 55?”*) and receive:

- Grounded explanations based on retrieved CPF policy text
- Simple, structured answers with disclaimers
- Responses generated by a **CrewAI policy explainer agent** with safety constraints

### 🔄 Data Flow & Implementation Details

1. The user enters:
   - a free-text CPF question, and
   - optional **age band** and **income band**.
2. The backend builds an **enriched query** (question + generic profile context).
3. The query is embedded and sent to the **vector store**.
4. The vector store returns the **top-k CPF policy chunks** (RAG).
5. The backend assembles a **safety-aware context block** that includes:
   - system instructions,
   - explicit anti–prompt-injection rules, and
   - the retrieved CPF text as reference.
6. A **CrewAI Agent** (“CPF policy explainer”) is created with:
   - a role and goal,
   - a backstory emphasising safety and non-advice.
7. A **Task** instructs the agent to:
   - read the context and question,
   - generate a grounded, Markdown-formatted explanation with caveats.
8. A **Crew** (with this agent + task) runs in **sequential** mode to produce the answer.
9. Streamlit displays the answer in a chat-style layout, with a reminder that it is educational only.
""")

st.subheader("📊 Flowchart – Use Case 1 (Graphviz)")

st.graphviz_chart("""
digraph {
  rankdir=TB;
  node [shape=box, style="rounded,filled", color="#4C72B0", fillcolor="#EAEFF7", fontsize=11];

  A [label="User enters CPF question\n(+ optional age/income)"];
  B [label="Backend enriches query\nwith profile context"];
  C [label="Embed query\n(OpenAI embeddings)"];
  D [label="Vector Store\ncosine similarity search"];
  E [label="Retrieve top-k\nCPF policy chunks"];
  F [label="Build safety-aware\ncontext block"];
  G [label="CrewAI Agent\n(CPF policy explainer)"];
  H [label="CrewAI Task\nreads context + rules"];
  I [label="Generate grounded\nMarkdown explanation"];
  J [label="Streamlit displays\nanswer to user"];

  A -> B -> C -> D -> E -> F -> G -> H -> I -> J;
}
""")

st.markdown("---")

# =====================================================================
# Use Case 2
# =====================================================================

st.header("🧮 Use Case 2 — Retirement Simulator (Projection + RAG + CrewAI Agent)")

st.markdown("""
### 🎯 Purpose

Help users run a **simplified projection** of CPF retirement savings and interpret the result in the
context of **BRS / FRS / ERS**, using a CrewAI agent for explanation.

### 🔄 Data Flow & Implementation Details

1. The user provides **numeric-only inputs**:
   - current age, planned retirement age,
   - current CPF savings,
   - monthly CPF contributions and expected growth,
   - optional target retirement income.
2. A **projection engine** runs a simple year-by-year simulation using these numbers and a blended
   interest assumption.
3. The final projected savings at retirement age are **classified** relative to the current FRS
   (e.g. “Below FRS”, “Around FRS”, “Between FRS and ERS”).
4. The backend builds a structured **numeric summary** (all values are treated as data, not instructions).
5. A controlled RAG query (constructed by the backend) is sent to the vector store to retrieve relevant
   policy chunks regarding:
   - retirement sums (BRS / FRS / ERS),
   - CPF LIFE conceptually,
   - relevant withdrawal or top-up information.
6. A **safety-aware context block** is constructed, containing:
   - numeric summary,
   - retrieved policy text,
   - strict safety rules (educational only, no advice, no override of instructions).
7. A **CrewAI Agent** (“CPF retirement simulation explainer”) is created with:
   - a clear goal (interpret the simulation safely),
   - a backstory emphasising limitations and non-advice.
8. A **Task** instructs the agent to:
   - explain the projection,
   - compare roughly against BRS/FRS/ERS,
   - highlight levers/trade-offs without recommending specific actions,
   - include a “Limitations & Disclaimer” section.
9. A **Crew** runs the agent and task in sequential mode to generate the explanation.
10. Streamlit displays:
    - a summary card,
    - a growth chart,
    - a data table,
    - the CrewAI-generated explanation.

All of this is clearly marked as **illustrative and non-official**.
""")

st.subheader("📊 Flowchart – Use Case 2 (Graphviz)")

st.graphviz_chart("""
digraph {
  rankdir=TB;
  node [shape=box, style="rounded,filled", color="#4C72B0", fillcolor="#EAEFF7", fontsize=11];

  A [label="User enters\nnumeric inputs"];
  B [label="Run projection engine\n(year-by-year)"];
  C [label="Compute projected CPF\nsavings at retirement"];
  D [label="Classify vs\nBRS / FRS / ERS"];
  E [label="Build numeric summary\n(illustrative only)"];
  F [label="Construct controlled\nRAG query"];
  G [label="Vector Store retrieves\nCPF policy chunks"];
  H [label="Build safety-aware\ncontext block"];
  I [label="CrewAI Agent\n(simulation explainer)"];
  J [label="CrewAI Task generates\nMarkdown explanation"];
  K [label="Streamlit displays\nsummary, chart, table,\nexplanation"];

  A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K;
}
""")

st.markdown("---")

st.header("📌 Safeguards & Safety Mechanisms")

st.markdown("""
To minimise the risks of LLM misuse and prompt injection:

- **Numeric-only inputs** for Use Case 2 prevent free-text injection into the simulation.
- For Use Case 1, user questions are wrapped in a **non-instructional context block**.
- CrewAI agents are given **strict system rules**:
  - no financial / legal advice,
  - no revealing of internal prompts,
  - no execution of hidden instructions from the retrieved text.
- Agents are instructed to:
  - stay grounded in the retrieved CPF context,
  - acknowledge uncertainty,
  - direct users to official CPF and gov.sg resources when needed.
""")

st.markdown("---")

st.header("🧩 Assumptions & Limitations")

st.markdown("""
- Projections are simplified (no OA/SA/MA breakdown).
- RAG corpus is curated, not exhaustive or guaranteed current.
- CrewAI agents cannot guarantee full factual accuracy.
- All outputs are for **education only** and cannot replace:
  - official CPF calculators,
  - personal CPF statements,
  - professional financial advice.
""")

st.markdown("---")

st.header("🏁 End of Methodology")

st.markdown("This page documents the data flows, implementation details, and agent orchestration used in both use cases.")
