import streamlit as st
import pandas as pd

from backend.rag import answer_policy_question

# NOTE: Do NOT call st.set_page_config here; it's already called in Home.py.

st.title("💬 CPF Policy Explainer")

st.markdown(
    """
Ask questions about CPF in **plain English** and get an explanation that is grounded in 
a curated set of CPF materials.

You can ask things like:

- *“What is the Full Retirement Sum (FRS)?”*  
- *“How much can I withdraw from CPF at age 55?”*  
- *“What happens to my CPF when I buy a flat?”*  

This page uses a Large Language Model (LLM) with **Retrieval-Augmented Generation (RAG)** 
to provide simplified, educational explanations.
"""
)

# ---------------------------------------------------------------------
# BRS / FRS / ERS explainer (collapsible)
# ---------------------------------------------------------------------
with st.expander("ℹ️ What are BRS, FRS, and ERS? (click to expand)"):
    st.markdown(
        """
CPF uses three benchmark amounts to indicate how much savings you might need for retirement:

**• Basic Retirement Sum (BRS)**  
- Baseline amount for basic monthly payouts.  
- Typically for members who **own a property** with sufficient lease.

**• Full Retirement Sum (FRS)**  
- Roughly **2 × BRS**.  
- Standard benchmark for members who do **not** rely on property for retirement income.

**• Enhanced Retirement Sum (ERS)**  
- Roughly **3 × BRS** (or higher, depending on policy changes).  
- For members who want the **highest CPF LIFE payouts** and can set aside more in CPF.

These sums are cohort-based (linked to the year you turn 55) and are used to estimate what kind of 
monthly payouts your CPF LIFE savings might support.
"""
    )

    comparison_df = pd.DataFrame(
        [
            {
                "Retirement Sum": "BRS",
                "Relative level": "1 × (baseline)",
                "Typical use case": "Basic payouts, usually for those who own a property.",
            },
            {
                "Retirement Sum": "FRS",
                "Relative level": "2 × BRS",
                "Typical use case": "Standard benchmark, especially if you don't have a qualifying property.",
            },
            {
                "Retirement Sum": "ERS",
                "Relative level": "3 × BRS",
                "Typical use case": "Optional higher savings for those who want higher payouts.",
            },
        ]
    )

    st.markdown("**Quick comparison:**")
    st.table(comparison_df)

    relative_df = pd.DataFrame(
        {
            "Retirement Sum": ["BRS", "FRS", "ERS"],
            "Relative amount": [1, 2, 3],
        }
    ).set_index("Retirement Sum")

    st.markdown("**Relative levels (illustration only):**")
    st.bar_chart(relative_df)

    st.caption(
        "Illustration only. The actual BRS / FRS / ERS dollar amounts depend on your cohort and CPF's official schedules."
    )

st.markdown("---")

# ---------------------------------------------------------------------
# Context form + question input
# ---------------------------------------------------------------------

st.subheader("📝 Ask a CPF Question")

st.markdown(
    """
You can optionally provide some simple context (age band and income band) to help the app 
tailor its explanation. All inputs are **generic** and **non-identifying**.
"""
)

with st.form("policy_explainer_form"):
    col1, col2 = st.columns(2)

    with col1:
        age_band = st.selectbox(
            "Age band (optional)",
            [
                "Prefer not to say",
                "Below 35",
                "35–44",
                "45–54",
                "55–64",
                "65 and above",
            ],
            index=0,
        )

    with col2:
        income_band = st.selectbox(
            "Monthly income band (optional)",
            [
                "Prefer not to say",
                "Below $2,500",
                "$2,500–$4,000",
                "$4,001–$6,000",
                "$6,001-$10,000"
                "Above $10,000",
            ],
            index=0,
        )

    question = st.text_area(
        "Your question about CPF",
        placeholder="Example: How much can I withdraw from my CPF at age 55?",
        height=120,
    )

    submitted = st.form_submit_button("Ask")

if submitted:
    if not question.strip():
        st.error("Please enter a question before clicking **Ask**.")
        st.stop()

    profile_context = {
        "Age band": age_band,
        "Income band": income_band,
    }

    st.markdown("### 💭 Your question")
    st.markdown(f"> {question.strip()}")

    with st.spinner("Thinking..."):
        answer = answer_policy_question(
            question=question,
            profile_context=profile_context,
        )

    st.markdown("### 🧾 Explanation")
    st.markdown(answer)

    st.info(
        """
**Reminder:**  
This explanation is generated by an LLM and based on simplified CPF information.  
It is meant **for education only** and may not capture all rules or your actual situation.  
Please verify details using official CPF and gov.sg websites and calculators.
"""
    )

else:
    with st.expander("💡 Not sure what to ask? Click for examples."):
        st.markdown(
            """
Try asking:

- *“What is the difference between BRS, FRS and ERS?”*  
- *“What happens to my OA and SA when I turn 55?”*  
- *“If I own an HDB flat, can I use BRS instead of FRS?”*  
- *“How does CPF LIFE work in simple terms?”*
"""
        )
